export const EXAMS = [
  {
    id_event: 3,
    title: "Assignment 3",
    grade: null,
    started_at: null,
    finished_at: null,
    questions: [
      { score: null, tries: null, answer: '""' },
      { score: null, tries: null, answer: '""' },
      { score: null, tries: null, answer: '""' },
      { score: null, tries: null, answer: '""' },
      { score: null, tries: null, answer: '""' },
      { score: null, tries: null, answer: '""' },
    ],
  },
  {
    id_event: 4,
    title: "Assignment 4",
    grade: null,
    started_at: null,
    finished_at: null,
    questions: [
      { score: null, tries: null, answer: '""' },
      { score: null, tries: null, answer: '""' },
      { score: null, tries: null, answer: '""' },
      { score: null, tries: null, answer: '""' },
      { score: null, tries: null, answer: '""' },
      { score: null, tries: null, answer: '""' },
    ],
  },
  {
    id_event: 5,
    title: "Assignment 5",
    grade: null,
    started_at: null,
    finished_at: null,
    questions: [
      { score: null, tries: null, answer: '""' },
      { score: null, tries: null, answer: '""' },
      { score: null, tries: null, answer: '""' },
      { score: null, tries: null, answer: '""' },
      { score: null, tries: null, answer: '""' },
      { score: null, tries: null, answer: '""' },
    ],
  },
  {
    id_event: 1,
    title: "Assignment 1",
    grade: 100,
    started_at: 1619379402118,
    finished_at: 1619379412118,
    questions: [
      { score: 100, tries: 9, answer: "test" },
      { score: 100, tries: 9, answer: "test" },
      { score: 100, tries: 9, answer: "test" },
      { score: 100, tries: 9, answer: "test" },
      { score: 100, tries: 9, answer: "test" },
      { score: 100, tries: 9, answer: "test" },
    ],
  },
  {
    id_event: 2,
    title: "Assignment 2",
    grade: null,
    started_at: null,
    finished_at: null,
    questions: [
      { score: null, tries: null, answer: '""' },
      { score: null, tries: null, answer: '""' },
      { score: null, tries: null, answer: '""' },
      { score: null, tries: null, answer: '""' },
      { score: null, tries: null, answer: '""' },
      { score: null, tries: null, answer: '""' },
    ],
  },
];
