import { library } from "@fortawesome/fontawesome-svg-core";
import {
  faBars,
  faLaptopCode,
  faUserCircle,
  faChevronDown,
  faChevronCircleRight,
  faCheckCircle,
  faTimes,
  faTimesCircle,
  faClock,
  faArrowLeft,
  faArrowCircleLeft,
  faArrowCircleRight,
  faUpload,
  faExclamationCircle,
  faStopwatch,
  faChevronRight,
  faChevronLeft,
} from "@fortawesome/free-solid-svg-icons";

library.add(
  faBars,
  faLaptopCode,
  faUserCircle,
  faChevronDown,
  faChevronCircleRight,
  faChevronRight,
  faChevronLeft,
  faCheckCircle,
  faTimes,
  faTimesCircle,
  faClock,
  faArrowLeft,
  faArrowCircleLeft,
  faArrowCircleRight,
  faUpload,
  faExclamationCircle,
  faStopwatch
);
